env:
  browser: true
  es2021: true
  node: true
# extends:
  # - plugin:react/recommended
  # - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  # sourceType: module
  project: './tsconfig.json'
plugins:
  - react
rules: {
  # "no-unused-vars": "off",
  # "quotes": ["single", "double"],
  "semi": "error",   #セミコロンの使用を許可するか否か
  # "@typescript-eslint/semi": "warn",
  # "@typescript-eslint/no-unused-vars": ["error", {
  #   "vars": "all",
  #   "args": "after-used",
  #   "ignoreRestSiblings": false
  # }] 
}