version: '3'
services:
  front-app:
    container_name: front-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: '3200'
      HOST: '0.0.0.0'
    command: sh -c "yarn install && yarn start"
    ports:
      - 3200:3200
    volumes:
      - .:/app
    # networks:
      # - api
# networks:
#   api:
#     external: true
  # storybook:
  #   build: .
  #   ports:
  #     - 6006:6006
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: yarn storybook