version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn start" # node_moduleを二重にinstallしないといけない

#   # storybook:
#   #   build: .
#   #   ports:
#   #     - 6006:6006
#   #   volumes:
#   #     - /app/node_modules
#   #     - .:/app
#   #   command: yarn storybook