version: '3'
services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    stdin_open: true
    tty: true
    restart: always
    command: sh -c "yarn install && yarn start"

volumes:
  node_modules_volume: